### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by shalpern1** [cthomasbabo/WebTech-Project#4]
Technical issues:
1. Brunch page does not have "Things to do" in the header.
2. The "About" header link does not work.
3. The "Things to do" header link does not work.
4. The "About Us" button on the home page does not work.
5. There is an image not appearing next to your logo.
6. When going from "Bars and Nightlife" back to "Home", it shows up as 404 not found.
7. The "Email" button on the home page does not work.

Overall feedback:
I think that anyone in Boston looking for new places to go and things to do would benefit from looking through this website. The layout is really organized and visually appealing. Perhaps adding a section for activities outside of restaurants/bars. This could fit in the "Things to do" section and could be shopping/outdoor activities/etc. Great job so far!

**Comment by cthomasbabo** [comment]
Thank you so much for the feedback! I was able to create my logo through text instead of an image, so it is appearing now & its animated! I also fixed the issues with the links, including the email button which will now direct you to the contact page.
